### ISSUE TITLE
X-Forwarded-Proto is ignored for the share links

### ISSUE THREAD

**Issue by BartVanBeurden** [epoupon/fileshelter#88]
When running fileshelter behind a reverse proxy, the `X-Forwarded-Proto` header is ignored. 

This causes the 'Public download link' and 'Private edit link' to contain the wrong protocol (http instead of https).  
Note that the actual href of the link is correct, but the displayed text is not. 

You can work around the issue by making sure your reverse proxy automatically redirects http to https, but this is not ideal.

**Comment by epoupon** [comment]
Hmm this is weird. Using the provided example in `INSTALL.md` file, I do get correct links (like in the demo site, by the way)
Did you change options in `fileshelter.conf` file as well? (Like `behind-reverse-proxy`)

**Comment by BartVanBeurden** [comment]
I agree, it is weird particularly because the other links are all correct.

Here's the relevant portion of my nginx config:

```apacheconf
proxy_pass http://localhost:8011;
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
```

Here's the relevant portion of `fileshelter.conf`

```apacheconf
listen-port = 5091;
listen-addr = "0.0.0.0";
behind-reverse-proxy = true;
original-ip-header = "X-Forwarded-For";
trusted-proxies =
(
        "127.0.0.1",
        "::1"
);
```

Here's the docker compose for fileshelter itself:

```yaml
version: "3"

services:
  fileshelter:
    container_name: fileshelter
    restart: unless-stopped
    image: epoupon/fileshelter:latest
    ports:
      - "8011:5091"
    volumes:
      - ./uploads:/var/fileshelter/
      - ./config/fileshelter.conf:/etc/fileshelter.conf
 ```

The `proxy_pass` forwards to http but I don't think that should matter?
